# Generated by Django 4.2.1 on 2023-06-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expediente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reevaluacion',
            name='paciente',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
