# Generated by Django 4.2.1 on 2023-06-21 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expediente', '0002_alter_reevaluacion_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='paraclinicos',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paraclinicos',
            name='pac',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Paciente'),
        ),
    ]
